### ISSUE TITLE
JF1367818433

### ISSUE THREAD

**Issue by huahuaShine** [zhongjiajie/DataX#33]
你好，请问怎么使用DATAX读取parquet格式的数据呢？

**Comment by zhongjiajie** [comment]
在本项目release下载最新编译的代码，然后将hdfsreader配置文件的fileType写成"par"即可

**Comment by huahuaShine** [comment]
我试了很多次都不行，方便加个微信吗？JF1367818433

**Comment by zhongjiajie** [comment]
已加，但是你没有同意
